id: I8CE7D477
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T01:29:24+00:00'
last_modified: '2022-06-09T06:50:42.817462+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN8167
  title: རྒྱུན་སྤྱོད་ཚན་རིག་ལག་རྩལ་སྐོར་གྱི་ཤེས་བྱ།༼ སྟོད་སྨད།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    217B:
      image_group_id: I1KG85661
      title: Volume 1 of rgyun spyod tshan rig lag rtsal skor gyi shes bya/(_stod
        smad/)
      total_pages: 186
      order: 1
      base_file: 217B.txt
    E395:
      image_group_id: I1KG85662
      title: Volume 2 of rgyun spyod tshan rig lag rtsal skor gyi shes bya/(_stod
        smad/)
      total_pages: 188
      order: 2
      base_file: E395.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
