id: P007870
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN8167
  title: རྒྱུན་སྤྱོད་ཚན་རིག་ལག་རྩལ་སྐོར་གྱི་ཤེས་བྱ།༼ སྟོད་སྨད།༽
  author: ''
  volumes:
    ac6ae800ade449dabf3ba448b69e951e:
      image_group_id: I1KG85661
      title: ''
      volume_number: 1
      total_pages: 186
    0306657dd1d541f6a04fc35b1365b7e2:
      image_group_id: I1KG85662
      title: ''
      volume_number: 2
      total_pages: 188
ebook_metadata:
  title: རྒྱུན་སྤྱོད་ཚན་རིག་ལག་རྩལ་སྐོར་གྱི་ཤེས་བྱ།༼ སྟོད་སྨད།༽
  author: ''
  sku: P007870
  cover: cover.jpg
  layers:
  - pagination
